# Generated by Django 5.0 on 2023-12-29 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='revoked',
        ),
        migrations.AlterField(
            model_name='token',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 12, 7, 245574, tzinfo=datetime.timezone.utc)),
        ),
    ]
