# Generated by Django 5.0 on 2023-12-30 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_remove_token_revoked_alter_token_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 8, 21, 33, 399575, tzinfo=datetime.timezone.utc)),
        ),
    ]
